### ISSUE TITLE
The starter theme need to init Timber\Timber

### ISSUE THREAD

**Issue by perruche** [studiometa/create-wordpress-project#10]
If you don’t initialize Timber, it will not register the proper filters for ACF and load the value directly from the database and you won’t have any values in your repeater field for exemple. 

Need to init the main Timber class to resolve this issue `new Timber\Timber();`

see the following issue for more details : https://github.com/timber/timber/issues/1652

**Comment by titouanmathis** [comment]
Fixed in c39234f.
