### ISSUE TITLE
Update the version of ACF 

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/create-wordpress-project#40]
In the `composer.json` update the package definition.

**Comment by perruche** [comment]
Sadly it's actually impossible to use a wildcard for version inside a `type: package`

I will manually update the version number for the moment. 

I could add a step to the install prompt saying to run `wp plugin update advancedcustomfields` ?

**Comment by titouanmathis** [comment]
Maybe we can use the [wp-premium/advanced-custom-fields-pro](https://github.com/wp-premium/advanced-custom-fields-pro) repository to always download the latest version with the following configuration: 

```json
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "acf/advanced-custom-fields-pro",
        "type": "wordpress-plugin",
        "version": "dev-master",
        "dist": {
          "type": "zip",
          "url": "https://github.com/wp-premium/advanced-custom-fields-pro/archive/master.zip"
        },
        "require": {
          "composer/installers": "^1.4"
        }
      }
    }
  ]
}
```

**Comment by ptt-homme** [comment]
As stated with @notjb, @studiometa/wordpress I think we should find a proper way to handle the download of ACF files. The repo proposed by @titouanmathis doesn't seem to be in sync with the latest version of ACF. This means we won't have the latest version till they bump it (the latest bump was 6 months ago). What do you think?

Should we create our own repository to fulfill this purpose?

**Comment by titouanmathis** [comment]
The repository has indeed not been updated since a long time. I checked the ACF Pro license, it seems that we are allowed to create our own repository to distribute the package.

I don't know if we can automate the release of any new version, but I think we doing it by hand for starter might be good enough. 

Who's up for the task? 🙂

**Comment by notjb** [comment]
I'm ready :)

**Comment by titouanmathis** [comment]
Here you go: https://github.com/studiometa/advanced-custom-fields-pro 😉
