### ISSUE TITLE
Ignore the generated wp-config.php file

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/create-wordpress-project#49]
The generated `web/wp-config.php` file should not be tracked by Git as it is generated by the `bin/source/wp-config-sample.php` file.

**Comment by perruche** [comment]
This is already the case [see here](https://github.com/studiometa/create-wordpress-project/blob/develop/template/_gitignore)

**Comment by titouanmathis** [comment]
My bad, it must have been a project specific bug.
