### ISSUE TITLE
Update the autoload path according to the chosen project slug

### ISSUE THREAD

**Issue by notjb** [studiometa/create-wordpress-project#51]
Update the `composer.json` file from `template` to have a working autoload path if the user chooses an other project slug than `studiometa`.

composer.json
```json
"autoload": {
    "psr-4": {
      "Studiometa\\": "web/wp-content/themes/<%= slug %>/app"
    }
  },
```

**Comment by notjb** [comment]
Closing the issue as it is fixed on `develop` :😉

**Comment by perruche** [comment]
I was waiting on #44 to do a release, but this is not going anywhere at this point. So maybe we should do a minor release to fix this

**Comment by notjb** [comment]
That would be nice even if this is not really urgent.
If I can help in any way, let me know ;)
