### ISSUE TITLE
Suggestion : remove the `wp-content` folder level

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/create-wordpress-project#69]
The path to the `wp-content` folder is editable as defined in our `wp-config.php` template : https://github.com/studiometa/create-wordpress-project/blob/develop/template/bin/source/wp-config-sample.php#L111-L113

I propose to define both the `WP_CONTENT_URL` and `WP_CONTENT_DIR` to point to the `web/` folder in order to simplify the project structure and to deviate a little more from the classic folder structure of WordPress.

We would then have the following folder tree:

```
web/ 
  themes/
  plugins/
  mu-plugins/
  .htaccess.example
  index.php
```

What is your take on the subject @studiometa/wordpress?

**Comment by ptt-homme** [comment]
@titouanmathis TBH I'm not really a fan of this proposition. The fact that our repo follows the WordPress structure gives to the developer some references that let him walks faster throughout the structure. For e junior dev, it's also a good point to have the WordPress structure, it's easier for him to understand how it works, and he can refer to what he learned without being disturbed.
For my personal POV, I don't really see what is the real interest behind this idea? Why do we need this new structure? Everyone here knows how WordPress works and where they can find theme and modules folders. With IDE, we have the abilities to find any files/folders by pressing Command+P.

**Comment by ptt-homme** [comment]
@studiometa/wordpress What do you think?

**Comment by KeziahMoselle** [comment]
Yes I agree with @ptt-homme, it sure is cleaner, but it has no real benefits for me

**Comment by perruche** [comment]
Agree that this does not change a lot. Shall we close this ?

**Comment by ptt-homme** [comment]
+1 to close this! @titouanmathis What do we do?

**Comment by titouanmathis** [comment]
😉
