### ISSUE TITLE
Change Timber base theme by Lumberjack base theme

### ISSUE THREAD

**Issue by ptt-homme** [studiometa/create-wordpress-project#85]
As mentioned by @titouanmathis earlier this week, this [repo](https://docs.lumberjack.rareloop.com/getting-started/installation) seems to do what we try to achieve using Timber and our customs implementations of Controller, Manager, Model and Services.
@studiometa/wordpress Do we need to give it a try?

**Comment by titouanmathis** [comment]
I think we can use this package without modifying all the architecture of our theme, but it would certainly help.

**Comment by perruche** [comment]
Lots of cool stuff in this indeed.
This probably needs an in depth discussion to identify pros and cons.

**Comment by perruche** [comment]
Should this issue be close ? it's stalled for a while

**Comment by titouanmathis** [comment]
Yes, I think we can close this issue.
