### ISSUE TITLE
Create ACF fields via CLI

### ISSUE THREAD

**Issue by ptt-homme** [studiometa/create-wordpress-project#86]
As discussed, it would be nice to find a solution to generate ACF fields config files using CLI as provided by Symfony or Laravel.
The goal : generate PHP files config containing all fields for a CPT or a taxonomy.
The cli asks what kind of content, what field type, the name of the field, custom values and write the answer in a file.
We should have a look if this mechanism exists on the WordPress world or make a little bit of R&D to have a Meta solution that fullfields this.
@studiometa/wordpress What's your take on that?

**Comment by perruche** [comment]
### Basic classification for fields type

**Most used fields**
- simple fields: image, text, wysiwyg, relation, link, page link, gallery
- complex fields: repeater, group

**Rest of the fields**
Checkbox, Radio Button, Select, True / False, Range, Text Area, Button Group, File, oEmbed, Color Picker, Date Picker, Date Time Picker, Google Map, Time Picker, Accordion, Flexible Content, Tab, Clone, Post Object, Taxonomy, User

**Comment by titouanmathis** [comment]
ACF Composer has a console command to generate a Field class: https://github.com/Log1x/acf-composer/blob/master/src/Console/FieldMakeCommand.php

**Comment by perruche** [comment]
The goal of this command would be to do more than just generating a file with a base structure.
Adding prompts to allow user to add fields in the command. Kinda like drupal does for `drupal generate:plugin:block` [see](https://drupalconsole.com/docs/ru/commands/generate-plugin-block)

To speed up even more the creation of the field groups

---

I did some research this morning, and i haven't found informations that this is possible to do with symfony console. I'm not sure it's possible to add prompts. Maybe @lusimeon you have done something linke this before ?

**Comment by lusimeon** [comment]
@perruche You can do prompt on Symfony command thanks to [question helper](https://symfony.com/doc/current/components/console/helpers/questionhelper.html) include in [command component](https://symfony.com/doc/current/components/console.html).

**Comment by perruche** [comment]
A tool is being made to handle this issue: 
https://github.com/studiometa/merlin
