### ISSUE TITLE
PhpcompatibilityWp sniffs for phpcs

### ISSUE THREAD

**Issue by lusimeon** [studiometa/create-wordpress-project#89]
Install [phpcompatibility/phpcompatibility-wp](https://github.com/PHPCompatibility/PHPCompatibilityWP) sniffs to PHP_CodeSniffer to alert on potential PHP compatibility issues.

Some [custom rulesets and specific test versions](https://github.com/PHPCompatibility/PHPCompatibility#using-a-custom-ruleset) can be set thanks to `phpcs.xml`.

Prevent PHP compatibility errors will make it easier to upgrade project's PHP version.

**Comment by titouanmathis** [comment]
Great idea! 👍
